parser: babel-eslint

env:
  browser: true
  node: true
  es6: true

plugins:
  - prettier
  - react

extends:
  - prettier
  - prettier/react

rules:
  prettier/prettier:
    - 1
    -
      trailingComma: none
      singleQuote: true
      semi: false
  react/jsx-uses-vars: error
  no-unused-vars: [error, {args: none}]
  prefer-const: [error, {ignoreReadBeforeAssign: true}]
